name: ImageBuilder
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v2
      with:
        url: http://127.0.0.1:8200
        tlsSkipVerify: true
        token: \${{ secrets.VAULT_TOKEN }}
        secrets: |
          secret/data/ci app_secret

    - name: Check Secrets
      run: |
        touch secrets.json
        echo "${{ steps.import-secrets.outputs.app_secret }}" >> secrets.json

    - name: Check json file format
      run: |
        echo
        cat secrets.json
